version: "3.9"

services:
  app:
    build: .
    container_name: myapp_web
    ports:
      - "5000:80"   # akses di localhost:5000
    environment:
      - ConnectionStrings__DefaultConnection=server=db;database=FMS_DB;user=root;password=secret;
      - ConnectionStrings__Redis=redis:6379
    depends_on:
      - db
      - redis
    networks:
      - myapp-network

  db:
    image: mysql:8.0
    container_name: myapp_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: secret@Bcd123
      MYSQL_DATABASE: FMS_DB
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - myapp-network

  redis:
    image: redis:7
    container_name: myapp_redis
    restart: always
    ports:
      - "6379:6379"
    networks:
      - myapp-network

volumes:
  db_data:

networks:
  myapp-network:
    driver: bridge
